service_account_name    = "example-service-account"
service_account_path    = "example-terraform"
GITHUB_REPOSITORY_OWNER = "openverse"
GITHUB_REPOSITORY       = "openverse/terraform-aws-data-ingestion"
GITHUB_REF              = "refs/heads/main"
GITHUB_ENV              = "production"
